name: Deploy to Kubernetes cluster
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_host:
        required: true
        type: string
      statefulset_name:
        required: false
        type: string
        default: "keycloak-keycloakx"
    secrets:
      CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID:
        required: true
      CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET:
        required: true
      KUBECONFIG_B64:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment_host }}
    steps:
      - uses: actions/checkout@v3
      - name: Establish cluster connection using cloudflared
        uses: hack-the-6ix/cloudflared-tcp-action@main
        with:
          cloudflare_tunnel_service_token_id: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          cloudflare_tunnel_service_token_secret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}
          cloudflare_tunnel_hostname: "k8sapi-moose.hackthe6ix.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'
      - name: Apply Kubeconfig
        run: |
          mkdir -p ~/.kube/
          echo $KUBECONFIG_B64 | base64 -d > ~/.kube/config
        shell: bash
        env:
          KUBECONFIG_B64: ${{secrets.KUBECONFIG_B64}}
      - name: Restart StatefulSet
        run: |
            kubectl rollout restart statefulset "$STATEFULSET_NAME"
        shell: bash
        env:
          STATEFULSET_NAME: ${{ inputs.statefulset_name }}
      - name: Remove Kubeconfig
        if: always()
        run: |
          rm -rf ~/.kube/config
        shell: bash
      - name: Shutdown cluster connection
        if: always()
        uses: hack-the-6ix/cloudflared-tcp-action/shutdown@main
